### ISSUE TITLE
Polyfill has problems with multiple selector rules

### ISSUE THREAD

**Issue by Rigo-m** [takamoso/postcss-aspect-ratio-polyfill#1]
This gets polyfilled correctly:
```css 
.image-container-1 {
  aspect-ratio: 1 / 1
}
.image-container-2 {
  aspect-ratio: 1 / 1;
}
```
This does not:

```css
.image-container-1, .image-container-2 {
  aspect-ratio: 1 / 1;
}
```
