### ISSUE TITLE
[bug] Fails when using `calc()` and variables

### ISSUE THREAD

**Issue by kerberjg** [takamoso/postcss-aspect-ratio-polyfill#5]
When using the CSS `calc()` function and variables to calculate `aspect-ratio` in my source CSS, the rule fails to compile properly

Input source:

```css
.card-cell {
            --card-width: 1;
            --card-height: 1;
            aspect-ratio: calc(var(--card-width) / var(--card-height));
}
```

Output:
```css
.card-cell::before {
    float: left;
    padding-top: calc(var(--card-width)NaN%var(--card-height));
    content: '';
}
```

Seems that this library doesn't work well when passing a single value to `aspect-ratio` which should be possible [according to the docs](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio): 

> If height and the preceding slash character are omitted, height defaults to 1

Since `padding-top` requires a percentage value, this can be fixed easily by multiplying the value by `100%` inside of another `calc()`, which results in working code.

Expected output:
```css
.card-cell::before {
    float: left;
    padding-top: calc( calc(var(--card-width) / var(--card-height) ) * 100%);
    content: '';
}
```
